### PR TITLE
Added Changes for promoting RHOC AppSRE grafana Dashboard to prod

### PR DESCRIPTION
**Pull request by shivamG640**
@lgarciaaco ,
Kindly review!

### CODE REVIEW

**Comment by heiko-braun** [comment]
@lgarciaaco , @dhirajsb can you help get this reviewed and deployed? With the CCS trial release today, it would be good to have the new dashboards in place

**Comment by dhirajsb** [comment]
@lgarciaaco will have to review these changes, since he would know what they mean and whether they are correct. @lgarciaaco or I can help get this into stage and then prod this week. 

@shivamG640 all changes go into stage first and then into production. There isn't a separate production branch where changes/PRs can be promoted directly in production.

**Comment by shivamG640** [comment]
@lgarciaaco, Can I merge this change?

**Review by lgarciaaco — APPROVED** [review]

**Comment by lgarciaaco** [comment]
@Shivam-Gu you don't need my approval to merge this kind of changes we have talked about the work in other channels. I don't want to be a blocker for this kind of work, I was on PTO yesterday we can avoid this kind of situation from happening.

**Comment by shivamG640** [comment]
Thanks for your comments @lgarciaaco

**Pull request merged**
